language: python
python:
  - "3.13"

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=ofektest
    - DOCKER_REPO=ofektest/ofektest
    - IMAGE_TAG=latest

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - pytest

before_deploy:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$IMAGE_TAG .

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/$DOCKER_REPO:$IMAGE_TAG
