language: python
python:
  - "3.13"

services:
  - docker

env:
  global:
    - DOCKER_REPO=ofektest/ofektest
    - IMAGE_TAG=latest

branches:
  only:
    - main

install:
  - pip install -r requirements.txt

script:
  - pytest

before_deploy:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$IMAGE_TAG .

deploy:
  provider: script
  script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$DOCKER_REPO:$IMAGE_TAG
